# Introduction {#sec:introduction}

The existence of a relationship between an individual's size and its weight is a central tenet in biology. 
While size is usually described as a one-dimensional measure (e.g. height or length), weight is a measure of a three-dimensional process. 


The study of the relationship between size and weight, allometry. 

Observations of size and weights are obtained during a number of scientific activities, and their respective measurements are highly influenced by the tools used to obtain them. 
While height and length measurements are readily obtained using a ruler, weight measurements require a scale. 
The precision associated with weight measurements is directly related to the instrument used, and scales usually have a minimum weight that they can report. 
Additionally, the design of scales has changed over time, leading to more precise measurements over time. 

In scientific monitoring programs such as annual marine ecosystem surveys conducted on research vessels, a large number of individuals of different marine taxa are measured and weighted. 
It is often the case that length measurements are available for all individuals caught, but weight measurements are only available from a subset of observations. 
Length-weight relationships are required to predict weight based on length observations. 
This is an essential analytical component of many stock assessments, since commercial landings and many reference points are in weight units but the underlying information collected are length measurements.

In the Gulf Region of Fisheries and Oceans Canada, an annual update of weight-at-size relationship parameters was historically done using a script written in SAS [@sas-citation]. 
This script evolved over a number of years and accreted ad hoc steps to identify errors and treat different taxa differently based on the number of observations available. 
This script was considered as the authoritative source to estimate the weight-at-size parameters used in weight predictions. 

We present a statistically sound framework to estimate length-weight relationship parameters, and apply it to observations of various fish and invertebrate taxa captured in the annual September ecosystem survey of the southern Gulf of St. Lawrence. 

<!-- https://en.wikipedia.org/wiki/Allometry -->


A cohesive approach is used to obtain length-weight relationship parameter estimates for taxa caught in the annual southern Gulf of St. Lawrence September survey. 
The approach utilises the number of available observations and the range of observed lengths and weights to determine where annual estimates can be derived with confidence. 
The sampling protocols used in the survey are incorporated in the framework so that sex-specific parameters can also be calculated when available data is available. 
When annual estimates can be meaningfully estimated, a single model is fitted to available observations and the parameter estimates are reported. 
The approach provides a robust and reproducible method that can be used to annually update length-weight relationship estimates.

Relevant literature citations [@Kulbicki-etal-2005; @Froese-2006; @Froese-etal-2011; @Jin-etal-2015; @Hajjej-2016; @Aydin-2018; @Yin-etal-2022; @Pauly-etal-2022].


issues to deal with 
- small sample size
- small size values and weight measurement precision
- limited size range
- taxonomic misidentification which requires grouping, this changes with time
- mismeasurement and transcription errors


uses:
1 - predict weight from size
  - list of taxa, annual weight-at-size predictor for observations in September

2 - flag outliers when entering data

do we need to include the stratification and/or a catch-weighted estimation?

