---
title: "Mixed-effects modelling of the weight-at-size relationship for fish and invertebrate taxa, with application to observations from the annual September ecosystem survey of the southern Gulf of St. Lawrence (1971-2025)"
french_title: ""
year: 2026
report_number: nnn
author: |
  Daniel Ricard^1^, 
  Matthew Robertson^2^, and 
  Tobie Surette^1^
author_list: "Ricard, D., Robertson, M. and Surette, T."
region: Gulf Region
french_region: Région du Golfe
isbn: ""
report_DOI: "##.####/xxxxx" # do not include https://doi.org/
address: |
  ^1^Gulf Fisheries Centre\
     Fisheries and Oceans Canada\
     343 Université Avenue\
     Moncton, New Brunswick, E1C 5K4, Canada\
  ^2^Marine Institute\
     Memorial University of Newfoundland\
     155 Ridge Road\
     St. John's, Newfoundland and Labrador, A1C 5R3, Canada
french_address: |
  ^1^Centre des Pêches du Golfe\
     Pêches et Océans Canada\
     343 avenue Université\
     Moncton, Nouveau Brunswick, E1C 9B6, Canada\
  ^2^Marine Institute\
     Memorial University of Newfoundland\
     155 Ridge Road\
     St. John's, Newfoundland and Labrador, A1C 5R3, Canada
phone: "(506) "
author_footnote: "Email: Daniel.Ricard@dfo-mpo.gc.ca | telephone: (506) 377-9527"
abstract: |
  A cohesive approach is used to obtain length-weight relationship parameter estimates for taxa caught in the annual southern Gulf of St. Lawrence September survey. The approach provides a robust and reproducible method that can be used to annually update length-weight relationship estimates used to make weight predictions from observed lengths.
french_abstract: |
  Voici le résumé.
citation_french: "Last, F.M. et Smith, A.B. 2026. Titre ici (Nom d'espèce latin). Rapp. tech. can. sci. halieut. aquat. nnn : v + 18 p. https://doi.org/##.####/xxxxx"
output:
 csasdowntex::techreport_pdf:
   french: false
   # copy_sty is a toggle to copy the style file from the csasdowntex package every time you compile
   # the document. If false, any changes you have made to the style file in your project
   # will remain between compilations. If true, your changes will be lost when you compile
   copy_sty: true
   # line_nums is a toggle to show line numbers on the left side of the page. 
   line_nums: true
   # lot_lof is a toggle to show/not show the lists of tables and figures at the
   # beginning of the document
   lot_lof: true
   # draft_watermark is a toggle to show/not show a DRAFT watermark across every page
   draft_watermark: true
   # highlight is the theme to use for code output. Must be one of the list given by:
   # pandoc --list-highlight-styles
   # which are:
   # pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock
   # or the name of a custom *.latex file which is most easily made by copying one from 
   # the csasdowntex library 'themes' directory, this directory on your machine:
   # file.path(.libPaths(), "csasdowntex", "themes")
   # to your working directory (the one containing index.Rmd)
   # To change the foreground text color, change the RGB value in the line containing
   # 'DefineVerbatimEnvironment'
   # To change background color, change the RGB values in the line containing 'shadecolor'
   highlight: tango
type:
  techreport
# ------------
# End of options to set
knit: (function(input, ...) {
       csasdowntex::render('_bookdown.yml')
      })
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdowntex)
```
