

The approach utilises the number of available observations and the range of observed lengths and weights to determine where annual estimates can be derived with confidence. The sampling protocols used in the survey are incorporated in the framework so that sex-specific parameters can also be calculated when appropriate data is available. When annual estimates can be meaningfully estimated, a single model is fitted to available observations and the parameter estimates are reported. 


The relationship between length and weight is dictated by the cubic nature of growth in three dimensions. 
Allometric models estimate the relationship between length and weight.

Mixed effects models have been used to estimate length-weight relationship parameters by other practitioners [@Lai-Hesler-2004; @Ma-etal-2017].

When year-specific estimates are desired, it is often the case that a length-weight relationship will be estimated using data for a specific year only. 
While this is a defensible method, it may be limited if not enough samples are available or available observations only cover a narrow range of lengths and weights. 
A superior alternative would be to use all available observations in the same model and obtain annual estimates whose uncertainty will reflect the data limitations.

The protocol used in the annual September survey of the southern Gulf of St. Lawrence contains sex-specific sampling for species that exhibit sexual dimorphism in growth. 
As such, sex-dependent parameters should be derived for these species.



## Sequential approach

For each taxon examined, the number of available paired observations of weight and size, and the range of their observed measurements, will determine whether a more complex model can be estimated.
The empirical contrast in length observations is used to classify each taxon to its most appropriate modelling approach.

A minimum number of samples must be available in order to meaningfully estimate $a$ and $b$ parameters.
The available length information must also cover a wide range of lengths so that estimated parameter values can be used in predictions.

The observations for each taxon come from a sampling protocol, and some of the observations are collected under a sex stratified design.

A sequential approach is used to determine whether a given taxon will use one of the following modelling options:

  1. Full Model: a sex- and time-dependent relationship is estimated
2. Time model: a time-dependent relationship is estimated
a. by year
b. by decade
3. Sex model: a sex-dependent relationship is estimated
4. Base model: a sex-independent and time-independent relationship is estimated

The models considered can be found in Table \@ref(tab:tablemodels).

